name: Generate Artefacts

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"
      - name: Build
        run: trunk build --release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gorske
          path: |
            dist/*
